export const config = {
  github: {
    username: "shivamkumarrrr",
    sortBy: "updated",
    limit: 8,
    exclude: {
      forks: false,
      projects: [],
    },
  },
  social: {
    linkedin: "https://www.linkedin.com/in/shiiiivam/",
    instagram: "https://www.instagram.com/shiivam_kumarr/",
    email: "shivamkumar17june@gmail.com",
  },
  resume: {
    fileUrl: "",
  },
  skills: [
    "Machine Learning",
    "Data Science",
    "Web Development",
    "Deep Learning",
    "Generative AI",
    "Python",
    "Pytorch",
    "Numpy",
    "Pandas",
    "Matpolotlib",
  ],
  education: [
    {
      institution: "Universität des Saarlandes",
      degree: "Bachelors degree",
      from: "2023",
      to: "2027",
    },
  ],
  themeConfig: {
    defaultTheme: "forest",
    disableSwitch: false,
    respectPrefersColorScheme: true,
    hideAvatarRing: false,
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "procyon",
    ],
  },

  // Optional Footer. Supports plain text or HTML.
  footer: `Copyright © 2023 Shivam Kumar`,
};
